version: '3.9'
name: "user_login_api_service"

services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: "ExamplePassword!"
    volumes:
      - ./sql/postgresql/create_database.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "1GB"

  backend:
    restart: always
    environment:
      - DB_URL=postgres://postgres:ExamplePassword!@db:5432/postgres
    depends_on:
      - db
    build:
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "256M"
      replicas: 4

  load-balancer:
    restart: always
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./.nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend